// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDna8Vb6h1Ageusq3qkm1t1Ew-CneSv7mA',
    appId: '1:34175926526:web:ea542e8a7065bb4c80e5af',
    messagingSenderId: '34175926526',
    projectId: 'ninja-brew-crew-coffe',
    authDomain: 'ninja-brew-crew-coffe.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-coffe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7CWfxWaOQdbHbHotqhlyYJc39TPj99xc',
    appId: '1:34175926526:android:60370f3f93bb0c5f80e5af',
    messagingSenderId: '34175926526',
    projectId: 'ninja-brew-crew-coffe',
    storageBucket: 'ninja-brew-crew-coffe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDslimGOwSJcR-EiB4RVPAw1Gvkz4IqvWI',
    appId: '1:34175926526:ios:ec45eb1e7ecacbf480e5af',
    messagingSenderId: '34175926526',
    projectId: 'ninja-brew-crew-coffe',
    storageBucket: 'ninja-brew-crew-coffe.appspot.com',
    iosBundleId: 'com.example.ninjaBrewCrewCoffre',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDslimGOwSJcR-EiB4RVPAw1Gvkz4IqvWI',
    appId: '1:34175926526:ios:f20c624d3725f31280e5af',
    messagingSenderId: '34175926526',
    projectId: 'ninja-brew-crew-coffe',
    storageBucket: 'ninja-brew-crew-coffe.appspot.com',
    iosBundleId: 'com.example.ninjaBrewCrewCoffre.RunnerTests',
  );
}
